# Generated by Django 3.1.5 on 2021-01-24 03:35

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_auto_20210122_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 24, 9, 5, 8, 894447)),
        ),
        migrations.AlterField(
            model_name='anwsers',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 24, 9, 5, 8, 889440)),
        ),
        migrations.AlterField(
            model_name='aptitude',
            name='question',
            field=ckeditor_uploader.fields.RichTextUploadingField(unique=True),
        ),
        migrations.AlterField(
            model_name='aptitude',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 24, 9, 5, 8, 894447)),
        ),
        migrations.AlterField(
            model_name='articles',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 24, 9, 5, 8, 884389)),
        ),
        migrations.AlterField(
            model_name='list',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 24, 9, 5, 8, 894447)),
        ),
    ]
