# Generated by Django 3.1.5 on 2021-01-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quora',
            name='tags',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
