# Generated by Django 3.1.5 on 2021-01-25 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discuss', '0002_quora_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='quora',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quora',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Quora_User', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
