# Generated by Django 3.1.5 on 2021-01-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0005_auto_20210125_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='quora',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Experience', 'Experience'), ('Question', 'Question'), ('Support', 'Support')], default='General', max_length=1000),
        ),
        migrations.AddField(
            model_name='quora',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
