# Generated by Django 3.1.5 on 2021-01-26 02:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0006_auto_20210125_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='quora',
            name='title2',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='quora',
            name='title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, unique=True),
        ),
    ]
