# Generated by Django 3.1.5 on 2021-01-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Playground', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playground',
            name='category',
            field=models.CharField(choices=[('Console', 'Console'), ('Frontend', 'Frontend')], default='Console', max_length=1000),
        ),
        migrations.AddField(
            model_name='playground',
            name='live',
            field=models.BooleanField(default=False),
        ),
    ]
