# Generated by Django 3.1.5 on 2021-01-20 02:50

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Playground', '0002_auto_20210119_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libraries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frontend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('HTML', 'HTMl'), ('CSS', 'CSS'), ('JavaScript', 'JavaScript'), ('SCSS', 'SCSS')], default='HTML', max_length=1000)),
                ('html', ckeditor.fields.RichTextField(blank=True)),
                ('css', ckeditor.fields.RichTextField(blank=True)),
                ('js', ckeditor.fields.RichTextField(blank=True)),
                ('scss', ckeditor.fields.RichTextField(blank=True)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Frontend_libraries', to='Playground.libraries', to_field='template')),
            ],
            options={
                'unique_together': {('method', 'language')},
            },
        ),
    ]
