# Generated by Django 3.1.5 on 2021-01-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Playground', '0003_frontend_libraries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontend',
            name='css',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='html',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='js',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='language',
            field=models.CharField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JavaScript', 'JavaScript'), ('SCSS', 'SCSS')], default='HTML', max_length=1000),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='scss',
            field=models.TextField(blank=True),
        ),
    ]
