# Generated by Django 3.1.5 on 2021-01-20 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Playground', '0004_auto_20210120_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendFrontend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField(blank=True)),
                ('css', models.TextField(blank=True)),
                ('js', models.TextField(blank=True)),
                ('scss', models.TextField(blank=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playground_frontend', to='Playground.playground')),
            ],
        ),
    ]
