# Generated by Django 3.1.5 on 2021-01-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Playground', '0005_extendfrontend'),
    ]

    operations = [
        migrations.AddField(
            model_name='playground',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
