# Generated by Django 3.1.5 on 2021-01-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Playground', '0006_playground_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='playground',
            name='embed',
            field=models.TextField(blank=True),
        ),
    ]
