# Generated by Django 3.1.5 on 2021-01-18 06:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='desciption',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
